language: clojure
lein: lein2
before_install:
- npm install karma karma-jasmine karma-phantomjs-launcher

script:
- lein2 cljsbuild once
- karma start --single-run --browsers PhantomJS
notifications:
  email:
    recipients:
      - z@caudate.me